name: Build and Sign on Windows

on:
  push:
    branches:
      - "signing"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/test.yaml"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: [self-hosted, Windows, X64]
    environment: sign
    steps:
      - name: Download Sources
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Get external libraries
        shell: cmd
        run: |
          git config --local "submodule.lib/windows_x64.update" "checkout"
          git submodule update --progress --init "lib/windows_x64"
          git lfs pull

      - name: Update
        shell: cmd
        run: make update
        
      - name: Build
        shell: cmd
        run: make

      - name: Sign
        uses: azure/trusted-signing-action@v0.3.20
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          endpoint: https://weu.codesigning.azure.net/
          trusted-signing-account-name: vscx-codesigning
          certificate-profile-name: bartvdbraak-blender
          files-folder: ${{ github.workspace }}
          files-folder-filter: exe,dll,pyd
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
